export const FETCH_AUTH_LOGIN_SUCCESS = "FETCH_AUTH_LOGIN_SUCCESS";
export const FETCH_AUTH_LOGIN_ERROR = "FETCH_AUTH_LOGIN_ERROR";
export const FETCH_AUTH_LOGIN_SAGA = "FETCH_AUTH_LOGIN_SAGA";

export const FETCH_AUTH_VALIDATE_EMAIL_SUCCESS = "FETCH_AUTH_VALIDATE_EMAIL_SUCCESS";
export const FETCH_AUTH_VALIDATE_EMAIL_ERROR = "FETCH_AUTH_VALIDATE_EMAIL_ERROR";
export const FETCH_AUTH_VALIDATE_EMAIL_SAGA = "FETCH_AUTH_VALIDATE_EMAIL_SAGA";

export const FETCH_VALIDATE_EMAIL_SUCCESS = "FETCH_VALIDATE_EMAIL_SUCCESS";
export const FETCH_VALIDATE_EMAIL_ERROR = "FETCH_VALIDATE_EMAIL_ERROR";
export const FETCH_VALIDATE_EMAIL_SAGA = "FETCH_VALIDATE_EMAIL_SAGA";

export const FETCH_AUTH_REGISTER_SUCCESS = "FETCH_AUTH_REGISTER_SUCCESS";
export const FETCH_AUTH_REGISTER_ERROR = "FETCH_AUTH_REGISTER_ERROR";
export const FETCH_AUTH_REGISTER_SAGA = "FETCH_AUTH_REGISTER_SAGA";

export const FETCH_RESET_PASSWORD_SUCCESS = "FETCH_RESET_PASSWORD_SUCCESS";
export const FETCH_RESET_PASSWORD_ERROR = "FETCH_RESET_PASSWORD_ERROR";
export const FETCH_RESET_PASSWORD_SAGA = "FETCH_RESET_PASSWORD_SAGA";

export const FETCH_GET_OTP_SUCCESS = "FETCH_GET_OTP_SUCCESS";
export const FETCH_GET_OTP_ERROR = "FETCH_GET_OTP_ERROR";
export const FETCH_GET_OTP_SAGA = "FETCH_GET_OTP_SAGA";

export const FETCH_AUTH_LOGOUT_SAGA = "FETCH_AUTH_LOGOUT_SAGA";
export const FETCH_AUTH_LOGOUT = "FETCH_AUTH_LOGOUT";

export const FETCH_AUTH_ITEMS = "FETCH_AUTH_ITEMS";
export const FETCH_AUTH_ITEMS_SUCCESS = "FETCH_AUTH_ITEMS_SUCCESS";
export const FETCH_AUTH_ITEMS_ERROR = "FETCH_AUTH_ITEMS_ERROR";
export const FETCH_AUTH_ITEMS_SAGA = "FETCH_AUTH_ITEMS_SAGA";
