export const FETCH_NEWS_SAGA = "FETCH_NEWS_SAGA";
export const FETCH_NEWS_SUCCESS = "FETCH_NEWS_SUCCESS";
export const FETCH_NEWS_ERROR = "FETCH_NEWS_ERROR";

export const FETCH_CATEGORIES_SAGA = "FETCH_CATEGORIES_SAGA";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const FETCH_CATEGORIES_ERROR = "FETCH_CATEGORIES_ERROR";

export const FETCH_SOURCES_SAGA = "FETCH_SOURCES_SAGA";
export const FETCH_SOURCES_SUCCESS = "FETCH_SOURCES_SUCCESS";
export const FETCH_SOURCES_ERROR = "FETCH_SOURCES_ERROR";

export const FETCH_SEARCH_SAGA = "FETCH_SEARCH_SAGA";
export const FETCH_SEARCH_SUCCESS = "FETCH_SEARCH_SUCCESS";
export const FETCH_SEARCH_ERROR = "FETCH_SEARCH_ERROR";

export const FETCH_CANCEL_FILTER_SAGA = "FETCH_CANCEL_FILTER_SAGA";
